### PR TITLE
Fixes NPE on reblog. Reblog returns Long id, construct post using tha…

### LINKED ISSUE #45: Error when reblog a post
I just start with Jumblr and i got an error ( NullPointer ) when i reblog a post. 

The problem happens because we try to parse the json object "post" while one recovers only the new post id. 

I made two changes: 
#### JumblrClient.java : Edit postReblog()
``` java
    public Post postReblog(String blogName, Long postId, String reblogKey, Map<String, ?> options) {
        if (options == null) {
            options = new HashMap<String, String>();
        }
        Map<String, Object> soptions = JumblrClient.safeOptionMap(options);
        soptions.put("id", postId.toString());
        soptions.put("reblog_key", reblogKey);

        // Edit here
        Long id = requestBuilder.post(JumblrClient.blogPath(blogName, "/post/reblog"), soptions).getIdFromReblog();
        return this.blogPost(blogName, id);
    }
```

#### ResponseWrapper.java : Add getIdFromReblog()
``` java
    
    public Long getIdFromReblog() {
        Gson gson = gsonParser();
        JsonObject object = (JsonObject) response;

        return gson.fromJson(object.get("id").toString(), Long.class);
    }
```

And the probleme has been solved ;)

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
**Fixes #45**: NPE when returning a `Post` from a reblog action. The response on reblog returns a JSON Object that only contains a `long id`. This uses the existing `getId()` method and constructs the reblogged `Post` using that and the reblogged blog name.

### CODE REVIEW

**Comment by ceykooo** [comment]
:+1: Tested with:
```
    Post p = client.postReblog("myblog.tumblr.com", 124665080661L, "ysPQDuZq");
    System.out.println(p.getId());
```

Before:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
	at com.tumblr.jumblr.responses.ResponseWrapper.get(ResponseWrapper.java:92)
	at com.tumblr.jumblr.responses.ResponseWrapper.getPost(ResponseWrapper.java:33)
	at com.tumblr.jumblr.JumblrClient.postReblog(JumblrClient.java:345)
	at com.tumblr.jumblr.JumblrClient.postReblog(JumblrClient.java:349)
	at com.tumblr.jumblr.Test.main(Test.java:36)
	... 6 more
```

After:
```
124756576351
```

File: src/main/java/com/tumblr/jumblr/JumblrClient.java [hunk 1]
```diff
@@ -342,7 +343,8 @@ public Post postReblog(String blogName, Long postId, String reblogKey, Map<Strin
         Map<String, Object> soptions = JumblrClient.safeOptionMap(options);
```
Comment (ceykooo) [inline src/main/java/com/tumblr/jumblr/JumblrClient.java]: @KevinTCoughlin can you update the javadoc for `blogName` while you're at it? It should be "the name of the blog to post _to_"

Comment (KevinTCoughlin) [inline src/main/java/com/tumblr/jumblr/JumblrClient.java]: Done.
